# Libraries

In [62]:
import numpy as np
import cmath
import math

# Task for 6-7

In [78]:
def simple_qr(matrix: np.array) -> np.array:
    q, r = np.linalg.qr(matrix)
    for _ in range(1_000):
        matrix = r @ q
        q, r = np.linalg.qr(matrix)
    return matrix

def get_roots(matrix: np.array) -> np.array:
    n = matrix.shape[0]
    approximated = np.vstack([simple_qr(matrix), np.zeros(n)])
    determinated = approximated.round(5)

    roots = np.zeros(n)
    i = 0
    while i < n:
        root = approximated[i][i]
        detr = determinated[i+1][i]
        if detr == 0:
            roots[i] = root
        else:
            # select block
            p = 1
            for j in range(i+1, n):
                if determinated[j+1][j] == 0:
                    break
                p += 1
            block = approximated[i:i+p+1, i:i+p+1]
            # p == 1 -> our target
            if p == 1:
                D = (block[1][1] + block[0][0])**2 - 4*(block[0][0]*block[1][1]-block[0][1]*block[1][0])
                # convert type
                if D < 0:
                    roots = roots.astype(complex)
                    l1 = (block[1][1] + block[0][0] - cmath.sqrt(D))/2
                    l2 = (block[1][1] + block[0][0] + cmath.sqrt(D))/2
                else:
                    l1 = (block[1][1] + block[0][0] - math.sqrt(D))/2
                    l2 = (block[1][1] + block[0][0] + math.sqrt(D))/2
                roots[i + p - 1] = l1
                roots[i + p - 0] = l2
            # p != 1 -> not our target
            else:
                __roots = np.linalg.eigvals(block)
                for j in range(p+1):
                    roots[i + j] = __roots[j]
            print(block)
            i += p
        i += 1
    return roots


In [80]:
n = 10
omega = 50

matrix = np.random.randint(-omega, omega, (n, n))
print(f"Initial matrix:\n{matrix}")
approximated_matrix = simple_qr(matrix)
print(f"Approximated matrix:\n{approximated_matrix.round(5)}")
roots = get_roots(matrix)
print(f"Function`s roots:\n{roots}")
eigen = np.linalg.eigvals(matrix)
print(f"True eigenvalues:\n{eigen}")

Initial matrix:
[[-50   5  21   6 -47  48 -19  13  31  49]
 [ 45  -6  36 -45  30 -37 -22  15  46  38]
 [-23  15  11   2 -28  37   3 -38  10   3]
 [  8  18 -40  24   5 -36  39   0 -49 -34]
 [  8 -21 -36  -5 -30 -23  33 -29 -32 -29]
 [ 32  14 -45   6  42  30  41   0 -39 -23]
 [-27 -36 -10 -37   8 -15   1 -30 -17 -11]
 [ 38 -30 -18  41  24  43  28 -32  -4 -40]
 [-14 -13   8 -44  42 -33 -41  45 -33  19]
 [ 47  42 -35  16  -9 -14  40 -35  44  25]]
Approximated matrix:
[[-9.446301e+01 -2.557466e+01  4.400223e+01  3.062915e+01  7.829320e+00
  -1.365399e+01  1.459837e+01 -2.354476e+01 -7.803362e+01 -4.724899e+01]
 [ 0.000000e+00  8.611941e+01  1.866761e+01  1.764785e+01 -6.458600e-01
   6.028097e+01  5.308479e+01 -2.489358e+01 -4.385223e+01 -4.703753e+01]
 [ 0.000000e+00  0.000000e+00 -2.567417e+01  7.197156e+01  4.850358e+01
  -2.090850e+01  2.592950e+01 -9.544120e+00 -2.646845e+01 -1.234800e-01]
 [-0.000000e+00 -0.000000e+00 -4.095504e+01 -6.097265e+01 -1.995965e+01
   6.319718e+01 -1.887120