# Libraries

In [113]:
import numpy as np
import scipy.linalg as la

# Task for 4 - 5 points

In [114]:
def get_random_real_matrix(n: int, epsilon: float) -> np.array:
    """
    This function returns a random real matrix with n rows and n columns.
    Also, it has real eigen values.

    :param n: rank of the matrix
    :param epsilon: it is -min and max values in matrix
    :return: np.array()
    """

    des = np.random.randn(n)
    s = np.diag(des)
    q = la.qr(np.random.rand(n, n))[0]
    result = q.T @ s @ q
    return result

def qr_algorithm(A, eps=1e-10, max_iter=1000):
    n = A.shape[0]
    Q, R = np.linalg.qr(A)
    S = R @ Q
    iter_count = 0
    while iter_count < max_iter and not np.allclose(A, S, atol=eps):
        A = S
        Q, R = np.linalg.qr(A)
        S = R @ Q
        iter_count += 1
    eigenvalues = np.diag(S)
    return eigenvalues

In [115]:
n = 5         # Size of the matrix
epsilon = 10   # It is -min and max values in matrix

matrix = get_random_real_matrix(n, epsilon)  # Generate random matrix
#matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Test matrix
matrix

array([[-0.15760005, -0.0566458 , -0.00715392, -0.0713411 , -0.06973394],
       [-0.0566458 , -0.24736269, -0.17527891, -0.20949473, -0.1470991 ],
       [-0.00715392, -0.17527891, -0.3957491 , -0.06983479, -0.04901721],
       [-0.0713411 , -0.20949473, -0.06983479, -0.01656929,  0.19006966],
       [-0.06973394, -0.1470991 , -0.04901721,  0.19006966, -0.081216  ]])

In [116]:
print(f'numpy`s eigenvalues: {np.linalg.eigvals(matrix).round(5)}')
print(f'function`s eigenvalues: {qr_algorithm(matrix, eps=1e-10, max_iter=1000).round(5)}')

numpy`s eigenvalues: [ 0.27952 -0.59226 -0.10596 -0.23724 -0.24256]
function`s eigenvalues: [-0.59226  0.27952 -0.24256 -0.23724 -0.10596]


In [117]:
del epsilon, n, qr_algorithm, get_random_real_matrix, la, matrix

# Task for 6 - 7

In [118]:
def qr_algorithm(A, eps=1e-10, max_iter=1000):
    n = A.shape[0]
    Q, R = np.linalg.qr(A)
    S = R @ Q
    iter_count = 0
    while iter_count < max_iter and not np.allclose(A, S, atol=eps):
        A = S
        Q, R = np.linalg.qr(A)
        S = R @ Q
        iter_count += 1
    eigenvalues = np.diag(S)
    return eigenvalues

In [119]:
n = 5         # Size of the matrix
epsilon = 10   # It is -min and max values in matrix

matrix = np.random.randint(-epsilon, epsilon, size=(n, n))  # Generate random matrix
matrix

array([[ -7,   1,  -4,   5,   8],
       [-10,   1,  -4,  -2,  -3],
       [  0,   2,  -7,   7,  -5],
       [ -9,   0,   9,   4,   2],
       [ -7,   8,   8,   1,  -8]])

In [120]:
print(f'numpy`s eigenvalues: {np.linalg.eigvals(matrix).round(5)}')
print(f'function`s eigenvalues: {qr_algorithm(matrix, eps=1e-10, max_iter=1000).round(5)}')

numpy`s eigenvalues: [  6.86626 +0.j       -1.58938+10.34571j  -1.58938-10.34571j
 -10.34375 +7.38637j -10.34375 -7.38637j]
function`s eigenvalues: [-11.40454  -9.28297   2.42299  -5.60175   6.86626]


In [121]:
del epsilon, n, qr_algorithm, matrix

# Task for 8

In [138]:
def qr(A, hauseholder=True):
    m, n = A.shape

    if hauseholder:
        Q = np.eye(m)
        for i in range(n - (m == n)):
            H = np.eye(m)
            H[i:, i:] = make_householder(A[i:, i])
            Q = np.dot(Q, H)
            A = np.dot(H, A)
    else:
        Q, A = np.linalg.qr(A)
    return Q, A

def make_householder(a):
    v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    v[0] = 1
    H = np.eye(a.shape[0])
    H -= (2 / np.dot(v, v)) * np.dot(v[:, None], v[None, :])
    return H


In [139]:
A = np.array([[1,2,3],[1,1,1]]).T
A

array([[1, 1],
       [2, 1],
       [3, 1]])

In [140]:
qr(A, hauseholder=True)

(array([[-0.26726124,  0.87287156,  0.40824829],
        [-0.53452248,  0.21821789, -0.81649658],
        [-0.80178373, -0.43643578,  0.40824829]]),
 array([[-3.74165739e+00, -1.60356745e+00],
        [-1.34739270e-16,  6.54653671e-01],
        [-1.48002270e-16,  5.96776529e-18]]))